version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: /api
    expose:
      - "3001"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    expose:
      - "5000"
    environment:
      - MONGO_URI=mongodb+srv://admin:Admin123@cluster0.v7tsihi.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
