version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - VITE_API_URL=http://backend:5000

    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://admin:Admin123@cluster0.v7tsihi.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
